'use client';

import { useState, useRef, useEffect } from 'react';
import { ChevronDown, Copy, Check, Download, Monitor, FileText, FileDown, ExternalLink } from 'lucide-react';
import { showToast } from '@/lib/use-toast';

interface CodeButtonProps {
  cloneUrl: string | null;
  fullName: string | null;
  selectedBranch: string;
  fileCount?: number;
  dependencyCount?: number;
  techStack?: string | null;
  repoDescription?: string | null;
  branchCount?: number;
}

export function CodeButton({
  cloneUrl,
  fullName,
  selectedBranch,
  fileCount,
  dependencyCount,
  techStack,
  repoDescription,
  branchCount,
}: CodeButtonProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!isOpen) return;
    const handler = (e: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [isOpen]);

  const displayUrl = cloneUrl || (fullName ? `https://github.com/${fullName}.git` : '');
  const archiveUrl = fullName
    ? `https://github.com/${fullName}/archive/refs/heads/${selectedBranch}.zip`
    : '';
  const desktopUrl = fullName
    ? `x-github-client://openRepo/https://github.com/${fullName}`
    : '';

  const handleCopyUrl = async () => {
    try {
      if (navigator.clipboard) {
        await navigator.clipboard.writeText(displayUrl);
      } else {
        const ta = document.createElement('textarea');
        ta.value = displayUrl;
        ta.style.position = 'fixed';
        ta.style.opacity = '0';
        document.body.appendChild(ta);
        ta.select();
        document.execCommand('copy');
        document.body.removeChild(ta);
      }
      setCopied(true);
      showToast('Clone URL copied to clipboard', 'success');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      showToast('Failed to copy URL', 'error');
    }
  };

  const handleDownloadZip = () => {
    if (archiveUrl) {
      window.open(archiveUrl, '_blank');
      showToast('Downloading ZIP archive...', 'info');
    }
  };

  const handleOpenDesktop = () => {
    if (desktopUrl) {
      window.location.href = desktopUrl;
      setTimeout(() => {
        window.open(`https://github.com/${fullName}`, '_blank');
      }, 500);
      showToast('Opening GitHub Desktop...', 'info');
    }
  };

  const generateReportContent = (format: 'markdown' | 'pdf') => {
    const date = new Date().toISOString().split('T')[0];
    const lines = [
      `# Repository Report: ${fullName || 'Unknown'}`,
      ``,
      `**Generated**: ${date}`,
      `**Branch**: ${selectedBranch}`,
      `**Format**: ${format.toUpperCase()}`,
      ``,
      `---`,
      ``,
      `## Overview`,
      ``,
      repoDescription || 'No description available.',
      ``,
      `---`,
      ``,
      `## Repository Statistics`,
      ``,
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Files | ${fileCount ?? 'N/A'} |`,
      `| Dependencies | ${dependencyCount ?? 'N/A'} |`,
      `| Branches | ${branchCount ?? 'N/A'} |`,
      `| Tech Stack | ${techStack || 'N/A'} |`,
      ``,
      `---`,
      ``,
      `## Branch Information`,
      ``,
      `- **Current Branch**: ${selectedBranch}`,
      `- **Clone URL**: ${displayUrl}`,
      ``,
      `---`,
      ``,
      `*Automated report generated by Repolyx Repository Intelligence*`,
      `*${date}*`,
    ];
    return lines.join('\n');
  };

  const handleDownloadReport = (format: 'markdown' | 'pdf') => {
    setIsOpen(false);
    const filename = `${fullName?.replace('/', '-') || 'repository'}-report.${format === 'markdown' ? 'md' : 'pdf'}`;
    const content = generateReportContent(format);
    const mimeType = format === 'markdown' ? 'text/markdown' : 'text/plain';
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast(`Report downloaded as ${format.toUpperCase()}`, 'success');
  };

  return (
    <div className="relative" ref={dropdownRef}>
      <div className="flex">
        <a
          href={displayUrl ? undefined : '#'}
          onClick={handleCopyUrl}
          className="flex items-center gap-1.5 rounded-l-lg bg-[#238636] px-3 py-1.5 text-xs font-semibold text-white hover:bg-[#2ea043] transition-colors border-r border-[#1a6b30]"
        >
          <Download size={12} />
          Code
        </a>
        <button
          onClick={() => setIsOpen(!isOpen)}
          className="flex items-center rounded-r-lg bg-[#238636] px-1.5 py-1.5 text-white hover:bg-[#2ea043] transition-colors"
        >
          <ChevronDown size={12} />
        </button>
      </div>

      {isOpen && (
        <div className="absolute right-0 top-full mt-1.5 w-72 rounded-lg border border-white/[0.08] bg-[#0d1117] shadow-elevated z-50 overflow-hidden">
          <div className="p-3 border-b border-white/[0.06]">
            <div className="flex items-center gap-2 rounded-md border border-white/[0.06] bg-white/[0.02] px-2.5 py-2 text-[11px] text-neutral-300 font-mono">
              <span className="flex-1 truncate">{displayUrl}</span>
              <button
                onClick={handleCopyUrl}
                className="shrink-0 text-neutral-500 hover:text-neutral-200 transition-colors"
                title="Copy URL"
              >
                {copied ? <Check size={12} className="text-emerald-400" /> : <Copy size={12} />}
              </button>
            </div>
          </div>

          <div className="py-1">
            <button
              onClick={() => { handleOpenDesktop(); setIsOpen(false); }}
              className="flex w-full items-center gap-3 px-3 py-2 text-xs text-neutral-300 hover:bg-accent/[0.06] hover:text-white transition-colors text-left"
            >
              <Monitor size={14} className="text-neutral-500 shrink-0" />
              <span className="flex-1">Open with GitHub Desktop</span>
            </button>

            <button
              onClick={() => { handleDownloadZip(); setIsOpen(false); }}
              className="flex w-full items-center gap-3 px-3 py-2 text-xs text-neutral-300 hover:bg-accent/[0.06] hover:text-white transition-colors text-left"
            >
              <Download size={14} className="text-neutral-500 shrink-0" />
              <span className="flex-1">Download ZIP</span>
            </button>
          </div>

          {fullName && (
            <a
              href={`https://github.com/${fullName}`}
              target="_blank"
              rel="noopener noreferrer"
              className="flex w-full items-center gap-3 px-3 py-2 text-xs text-neutral-500 hover:bg-accent/[0.06] hover:text-white transition-colors border-t border-white/[0.06]"
            >
              <ExternalLink size={14} className="shrink-0" />
              <span className="flex-1">Open on GitHub</span>
            </a>
          )}

          <div className="border-t border-white/[0.06]">
            <div className="px-3 py-1.5 text-[9px] font-semibold text-neutral-500 uppercase tracking-widest">
              Download Report
            </div>
            <button
              onClick={() => handleDownloadReport('markdown')}
              className="flex w-full items-center gap-3 px-3 py-2 text-xs text-neutral-300 hover:bg-accent/[0.06] hover:text-white transition-colors text-left"
            >
              <FileText size={14} className="text-neutral-500 shrink-0" />
              <span className="flex-1">Markdown</span>
            </button>
            <button
              onClick={() => handleDownloadReport('pdf')}
              className="flex w-full items-center gap-3 px-3 py-2 text-xs text-neutral-300 hover:bg-accent/[0.06] hover:text-white transition-colors text-left"
            >
              <FileDown size={14} className="text-neutral-500 shrink-0" />
              <span className="flex-1">PDF</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
